### PR TITLE
Granite 6.2.0 jammy

### PR DESCRIPTION
**Pull request by 13r0ck**
We will have to reshuffle the branches here. This will be pushed to master. and current master will become master_focal

[According to @isantop](https://github.com/pop-os/granite/pull/2#issuecomment-1442244385) the most important things to test would be the Installer and Pop_Shop. Eddy would probably be a good idea as well.

### CODE REVIEW

**Review by jacobgkau — APPROVED** [review]
The Pop!_Shop, Eddy, and the installer all still work fine with this library updated.

Only tested on Jammy since it was stated Focal will be keeping its current master branch/version.

**Review by jackpot51 — APPROVED** [review]

**Comment by 13r0ck** [comment]
@jackpot51 I don't have permissions to merge this into master

**Comment by leviport** [comment]
@13r0ck do you have sufficient permissions now?

**Comment by 13r0ck** [comment]
nope

**Comment by leviport** [comment]
I think it was because force pushes were turned off. You should be good to go now.

**Comment by 13r0ck** [comment]
That worked thanks!

**Pull request merged**
